# Generated by Django 5.1.3 on 2024-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutguide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
