# Generated by Django 5.1.3 on 2024-12-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutguide', '0002_workout_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tip',
        ),
    ]
